version: '3'

services:
  nodejs:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    image: frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000"
    command: npm start